import { Image} from 'primereact/image';
import { Button } from 'primereact/button';
import React from "react";
import { color } from "./utils/info";
import Link from "next/link";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Smart Kaj | Error",
  description: "Generated by create next app",
};
export default function NotFound() {
  return (
    <main className="h-screen flex items-center justify-center">
      <div>
        <h1 className="font-bold text-5xl">Hmm,that did not work.</h1>
        <p className="text-xl text-gray-500 mt-3">
          The page you are looking for cannot be found
        </p>
        <div className="flex justify-center">
          <Image
            src="https://img.freepik.com/free-vector/oops-404-error-with-broken-robot-concept-illustration_114360-1932.jpg?size=338&ext=jpg&ga=GA1.1.1826414947.1699228800&semt=ais"
            width="300"
            className="mt-5 mx-auto"
            alt="Not Found Image"
          />
        </div>
        <Link href="/" className="flex items-center justify-center mt-3">
          <Button
            style={{ background: color.background.secondary }}
            className="text-white w-1/2"
          >
            Back to Home
          </Button>
        </Link>
      </div>
    </main>
  );
}
